USE BLOCKCHAINS_CRIPTOMOEDAS;


-- 



CREATE TABLE BLOCKCHAIN(
    IDBLOCKCHAIN INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL UNIQUE,
    VALOR DOUBLE(20,3) NOT NULL
);

CREATE TABLE CRIPTOMOEDA(
    IDCRIPTOMOEDA INT PRIMARY KEY AUTO_INCREMENT,
    SIGLA CHAR (4) NOT NULL UNIQUE,
    VALOR DOUBLE(20,3) NOT NULL,
    PROTOCOLO VARCHAR(40),
    ID_BLOCKCHAIN INT,
    
    FOREIGN KEY(IDCRIPTOMOEDA)
    REFERENCES BLOCKCHAIN(IDBLOCKCHAIN)
);

CREATE TABLE TOKEN(
    IDTOKEN INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL UNIQUE,
    SIGLA CHAR (4) NOT NULL UNIQUE,
    VALOR DOUBLE(20,3) NOT NULL,
    PROTOCOLO VARCHAR(40),
    ID_BLOCKCHAIN INT,
	
    FOREIGN KEY(ID_BLOCKCHAIN)
    REFERENCES BLOCKCHAIN(IDBLOCKCHAIN)
    
);





---------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------BLOCKCHAIN
DELIMITER $$
CREATE PROCEDURE REGISTRAR_BLOCKCHAIN(PROC_NOME VARCHAR(40),PROC_VALOR DOUBLE(20,3))
BEGIN
	INSERT INTO BLOCKCHAIN VALUES(NULL,PROC_NOME,PROC_VALOR);
END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE DELETAR_BLOCKCHAIN(PROC_IDBLOCKCHAIN INT)
BEGIN
    DELETE FROM BLOCKCHAIN WHERE IDBLOCKCHAIN = PROC_IDBLOCKCHAIN;
END
$$
DELIMITER ;



DELIMITER $
CREATE PROCEDURE ATUALIZAR_BLOCKCHAIN(PROC_NOME VARCHAR (30),PROC_VALOR DOUBLE(20,3))
BEGIN
	UPDATE BLOCKCHAIN SET NOME = PROC_NOME WHERE NOME = PROC_NOME;
    UPDATE BLOCKCHAIN SET VALOR = PROC_VALOR WHERE NOME = PROC_NOME;
END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE RELATORIO_BLOCKCHAIN()
BEGIN
    SELECT IDBLOCKCHAIN,NOME,VALOR FROM BLOCKCHAIN;

END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE PESQUISAR_BLOCKCHAIN(PROC_NOME VARCHAR(40))
BEGIN
	SELECT IDBLOCKCHAIN,NOME,VALOR FROM BLOCKCHAIN WHERE NOME = PROC_NOME;
END
$$
DELIMITER ;









----------------------------------------------------------CRIPTOMOEDAS

DELIMITER $$
CREATE PROCEDURE REGISTRAR_CRIPTOMOEDA(PROC_SIGLA CHAR(4),PROC_VALOR DOUBLE(20,3),PROC_PROTOCOLO VARCHAR(40),PROC_ID_BLOCKCHAIN INT)
	BEGIN
		INSERT INTO CRIPTOMOEDA VALUES(NULL,PROC_SIGLA,PROC_VALOR,PROC_PROTOCOLO,PROC_ID_BLOCKCHAIN);
    END
$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE DELETAR_CRIPTOMOEDA(PROC_IDCRIPTOMOEDA INT)
BEGIN
    DELETE FROM CRIPTOMOEDA WHERE IDCRIPTOMOEDA = PROC_IDCRIPTOMOEDA;
END
$$
DELIMITER ;


DELIMITER $
CREATE PROCEDURE ATUALIZAR_CRIPTOMOEDA(PROC_SIGLA CHAR(4),PROC_VALOR DOUBLE(20,3), PROC_PROTOCOLO VARCHAR(40))
BEGIN
	UPDATE CRIPTOMOEDA SET SIGLA = PROC_SIGLA WHERE SIGLA = PROC_SIGLA ;
    UPDATE CRIPTOMOEDA SET VALOR = PROC_VALOR WHERE SIGLA = PROC_SIGLA ;
    UPDATE CRIPTOMOEDA SET PROTOCOLO = PROC_PROTOCOLO WHERE SIGLA = PROC_SIGLA;
END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE RELATORIO_CRIPTOMOEDA()
BEGIN
    SELECT IDCRIPTOMOEDA,SIGLA,PROTOCOLO,ID_BLOCKCHAIN FROM CRIPTOMOEDA;

END
$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE PESQUISAR_CRIPTOMOEDA(PROC_SIGLA CHAR(4))
BEGIN
	SELECT IDCRIPTOMOEDA,SIGLA,PROTOCOLO,ID_BLOCKCHAIN FROM CRIPTOMOEDA WHERE SIGLA = PROC_SIGLA;
END
$$
DELIMITER ;


-------------------------------------------------------TOKENS
DELIMITER $$
CREATE PROCEDURE REGISTRAR_TOKEN(PROC_NOME VARCHAR(40),PROC_SIGLA CHAR(4),PROC_DATA_LANCAMENTO DATE,PROC_VALOR DOUBLE(20,3),PROC_PROTOCOLO VARCHAR(40),PROC_IDBLOCKCHAIN INT)
BEGIN
	INSERT INTO TOKEN VALUES(NULL,PROC_NOME,PROC_SIGLA,PROC_DATA_LANCAMENTO,PROC_VALOR,PROC_PROTOCOLO,PROC_IDBLOCKCHAIN);
END
$$
DELIMITER ;







-- 

CALL REGISTRAR_BLOCKCHAIN('Bitcon',5966031716.019);
CALL REGISTRAR_BLOCKCHAIN('Ethereum',2470318691.555);
CALL VISUALIZAR_BLOCKCHAIN('ETH');
CALL REGISTRAR_BLOCKCHAIN('Bitcon',5966031716.019);
CALL REGISTRAR_BLOCKCHAIN('Ethereum',2470318691.555);
CALL REGISTRAR_CRIPTOMOEDA('BTC',315134.67,'P2P - Algoritmo SHA-256',1);
CALL REGISTRAR_CRIPTOMOEDA('ETH',20872.89,'ERC-20 - Proof-of-work',2);
CALL PESQUISAR_BLOCKCHAIN('Bitcon');
CALL RELATORIO_BLOCKCHAIN;
CALL DELETAR_BLOCHAIN(1);



